### ISSUE TITLE
Typo in SceneGraphBuilder.groovy

### ISSUE THREAD

**Issue by shnplr** [groovyfx-project/groovyfx#29]
Line 154-
                                case Worker.State.CANCELED:
                                    System.out.println(wv.engine.loadWorker.message);
                                    wv.engine.loadWorker.stateProperty().removeListener(this);
                                    break;

S/be CANCELLED (with 2 x L's)

**Comment by aalmiray** [comment]
For reference http://grammarist.com/spelling/cancel/

**Comment by shnplr** [comment]
https://docs.oracle.com/javase/8/javafx/api/javafx/concurrent/Worker.State.html#CANCELLED

**Comment by shnplr** [comment]
Also, perhaps call to 'System.out' should be replaced with LOG.debug|info (2 places).
