### ISSUE TITLE
Add builder support for javafx.scene.control.ButtonBar

### ISSUE THREAD

**Issue by shnplr** [groovyfx-project/groovyfx#32]
groovy.util.FactoryBuilderSupport createNode
WARNING: Could not find match for name 'buttonBar'
e.g.

    buttonBar {
        button buttonData: OK
        button buttonData: APPLY
        button buttonData: CANCEL
    }

I'm trying to use this inside a Griffon application if it makes any difference

**Comment by aalmiray** [comment]
Fixed with https://github.com/groovyfx-project/groovyfx/commit/6423cb9de6ff17dce55ddba3b380118eaab10504
