### ISSUE TITLE
Link(s) to mailing list are obsolete

### ISSUE THREAD

**Issue by msgilligan** [groovyfx-project/groovyfx#40]
There are references and links in the following places to Codehaus mailing lists:

* Developer Wiki https://github.com/groovyfx-project/groovyfx/wiki

(Looks like there's only one place, but I thought I saw it somewhere else. On http://groovyfx.org the *Mailing Lists* link points to the *Mailing Lists* page on the groovy-lang.org website. Are those the correct lists now for GroovyFX discussion?)

**Comment by kastork** [comment]
The link to the getting started guide is also broken (this is on the site home page).

`http://groovyfx.org/docs/guide/gettingStarted.html`

**Comment by msgilligan** [comment]
@kastork I created a PR that fixes that broken link: https://github.com/groovyfx-project/groovyfx-project.github.com/pull/10

@russel  @aalmiray et. al. If you tell me what the current mailing list is, I will create a pull request for that fix, too.

**Comment by russel** [comment]
There are no GroovyFX specific mailing lists now. The traffic was so low that when Codehaus demised we agreed to just use the Groovy list with a [GroovyFX] Subject prefix.

**Comment by russel** [comment]
@kastork I believe @msgilligan 's pull request on the website is now merged.

**Comment by msgilligan** [comment]
@russel I created this Wiki Page based upon your response: https://github.com/groovyfx-project/groovyfx/wiki/Mailing-Lists

If it looks good I'll create a pull request for the **Mailing Lists** link on the website to point to this wiki page instead of (confusingly IMHO) pointing directly to the list of 4 Groovy mailing lists.

**Comment by russel** [comment]
@msgilligan That definitely works for me. Thanks for proposing this fix. I'll commit a pull request as soon as it appears here.

**Comment by msgilligan** [comment]
@russel I just made some additional fixes on the [Wiki home page](https://github.com/groovyfx-project/groovyfx/wiki) (other links and references to CodeHaus, see wiki history for changes)

**Comment by msgilligan** [comment]
@russel And here's the PR for the mailing list link on the Github page site: https://github.com/groovyfx-project/groovyfx-project.github.com/pull/12

**Comment by russel** [comment]
@msgilligan  Duly merged and tested. Thanks for spotting this and fixing it.
