### ISSUE TITLE
Github project page title still says "JavaFX 2.0"

### ISSUE THREAD

**Issue by msgilligan** [groovyfx-project/groovyfx#43]
The title on [this page](https://github.com/groovyfx-project/groovyfx) still says 

> A library for writing JavaFX 2.0 applications in the Groovy language

I'd send a pull request for this fix, but it requires someone with repo admin privilege to edit via the Github Web UI.

**Comment by russel** [comment]
I believe I am supposed to have appropriate privileges but I do not see an edit button – but then the GitHub UI changes so often I may just be missing it.

**Comment by msgilligan** [comment]
I just checked on a repo I have admin access on and the edit link appears on the main page just to the right of title. Maybe you don't have access. Should we tag someone or assign this issue to someone. We definitely want GroovyFX to look like an active/current project. It should definitely have an **8** there.

**Comment by russel** [comment]
@msgilligan I have a request in to @aalmiray to find out who has "big boss" privilege as clearly I don't. I had assumed everyone in the team that could commit to the repository could also amend things, but apparently commit and admin are different roles and privileges.

**Comment by russel** [comment]
@msgilligan I have been inculcated into the mysteries of core and appended to the membership of core. You will note that s/2.0/8/ has been achieved.

**Comment by msgilligan** [comment]
Awesome! You should also change the link to be GroovyFX.org -- someone's paying for the domain, let's use it!

**Comment by russel** [comment]
Good point. Done.
